---

- name: add ppa for install openjdk-8
  shell: add-apt-repository ppa:openjdk-r/ppa -y; apt-get update
  when: ansible_distribution_major_version == "14"

- name: Install OpenJDK
  apt: name=openjdk-8-jdk state=present

